name: Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build-${{ matrix.architecture }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64-unknown-linux-gnu, thumbv7em-none-eabihf]
        target: [--all-targets, --lib]
        exclude:
          - target: --all-targets
            architecture: thumbv7em-none-eabihf
          - target: --lib
            architecture: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.architecture }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: ${{ matrix.target }} --target ${{ matrix.architecture }}
